
import { SearchProvider } from '@/components/contexts/SearchContext';
import { CartProvider } from '@/components/contexts/CartContext';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "MORENT",
  description: "Generated by create Hashir",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SearchProvider>
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </SearchProvider>
      </body>
    </html>
  );
}

